### ISSUE TITLE
Check Sample!

### ISSUE THREAD

**Issue by ggoral** [madhurjain/passport-local-sequelize#12]
Hi @madhurjain ,

There is a complete sample of this module on my account, please check if everything is fine, works fine for me. 

I've respected the official skeleton of Sequelize
 ```
/config/config.json
/migratations/
/models/index.js
```
But I've found a conflict with `models/index.js`, Can you help me to fix this conflict? I really need to try to respect the sequelize scheme on the user.js module.

https://github.com/ggoral/easy-passport-local-sequelize-express4-sample

 Best regards!

**Comment by lefnire** [comment]
Thanks for the sample @ggoral, very useful

**Comment by ggoral** [comment]
In another example, I've tried to copy this sample but without install 'passport-local-sequelize' package, because is not necessary, with a simple configuration file you can get the same result.

Thank for your reply @lefnire !

**Comment by lefnire** [comment]
@ggoral do you have that sample public? Would love to take a look, having a hulluvatime with this repo

**Comment by ggoral** [comment]
@lefnire yes, take a look here https://github.com/ggoral/try-passport-with-sequelize
