### ISSUE TITLE
Hash is too long for VARCHAR (255)

### ISSUE THREAD

**Issue by Atrox** [madhurjain/passport-local-sequelize#21]
Hello,

I get the following error if I try to register: `SQL Error 1406: Data too long for column 'hash' at row 1`
If I change the hash column from `VARCHAR` to `TEXT` everything works as expected.

I'm using the default model (.defineUser). I think this is not expected?

Thanks,
Atrox

**Comment by philotas** [comment]
same here. How long can the hash become or is it always the same? Knowing the length instead of TEXT one could use DataTypes.STRING(1024) for example

**Comment by carlitux** [comment]
depends on keylen option default is 512 https://github.com/madhurjain/passport-local-sequelize/blob/master/lib/passport-local-sequelize.js#L13

**Comment by lefnire** [comment]
I'm running [my fork](https://github.com/lefnire/passport-local-sequelize) in [production](https://jobpigapp.com/), _definitely_ must be `TEXT` instead of `STRING` ([diff](https://github.com/lefnire/passport-local-sequelize/commit/4344a3e61fff5687c20ddfac6249e0aa4c2ffd24)).

**Comment by madhurjain** [comment]
@lefnire could you send a pull request? Been a while I last used this library or sequelize.

**Comment by busheezy** [comment]
Can this be pushed to npm?
