### ISSUE TITLE
Interested in ES6 upgrade?

### ISSUE THREAD

**Issue by lefnire** [madhurjain/passport-local-sequelize#30]
My [fork](https://github.com/lefnire/passport-local-sequelize) is all ES6, plus fixes (most which I just PR'd) and I'll be keeping up with. I'd be happy to co-maintain the project if desired. My only caveat is I drank the cool-aid and went all ES6 on the repo. I know many may have qualms if they're running Node < v4, so I thought I'd bounce it off you - gauge interest before submitting a PR. If not interested, feel free to close ticket :)

**Comment by madhurjain** [comment]
I am on a hiatus currently so it would be great if you can co-maintain this project. We can branch off the legacy version and merge ES6 to master.

**Comment by lefnire** [comment]
Fantastic! Add me to the project sometime and I'll go ahead & do that in time. To confirm, you want to branch (and shall I tag too?) master to, say `es5`; then continue with ES6 updates on master?

**Comment by lefnire** [comment]
@madhurjain sorry I haven't been available at all like I promised :( I left the project I was using this module for, so haven't had incentive unfortunately. Feel free to boot me, you may wanna take a peek at the PR list - got some good ones needin' review

**Comment by madhurjain** [comment]
@lefnire No problem Tyler. I have some time now to look into all the pull requests and pending issues. I will take it up from here. Thanks for your help!

**Comment by dengue8830** [comment]
for anyone who came to this issue searching a way to use promises, for the user register api i find this way:

```
const registerUser = promisify(User.register);
const user = await registerUser.call(User, 'username', 'pass');
```
