### ISSUE TITLE
Usage of crypto.pbkdf2 without specifying a digest is deprecated

### ISSUE THREAD

**Issue by heygrady** [madhurjain/passport-local-sequelize#32]
```
DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
```

There is an unmerged pull request that addresses this issue: https://github.com/madhurjain/passport-local-sequelize/pull/31/commits/11a72900464eb76ee8ccb178bdb5a5c71f3554ff

**Comment by amnotafraid** [comment]
When I changed over from Node 4.2 to Node 6.0, I started getting this warning. From the comments, it was unclear which version or even which package I needed to update to in order to not get the warning.

However, I changed from this:
```
  1 this.password = crypto.pbkdf2Sync (
  2                   password,
  3                   this.salt,
  4                   1000,
  5                   64).toString('hex');
```
to this:
```
  1 this.password = crypto.pbkdf2Sync 
  2       (password,
  3        this.local.salt,
  4        1000,
  5        64,
  6        'sha1').toString('hex');
```
and I was okay.

**Comment by shanehughes3** [comment]
Is there something preventing #31 from being merged to fix this?

**Comment by isTravis** [comment]
Thankful for #31 - but in this case why not continue to emulate passport-local-mongoose and allow digestAlgorithm to be an option. You can see their single line in the config here: [https://github.com/saintedlama/passport-local-mongoose/blob/master/index.js#L15](https://github.com/saintedlama/passport-local-mongoose/blob/master/index.js#L15)

I have a handful of user accounts that are grandfathered in to SHA1 - so being forced into sha256 makes the library unusable for me.
