### ISSUE TITLE
Sequelize v4 - Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ashah888** [madhurjain/passport-local-sequelize#37]
With the latest version (4+) of Sequelize, there seems to be an error, probably due to neccessary migrations not being done yet.

Cannot read property 'prototype' of undefined

at Object.attachToUser (/....../node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:82:24)

**Comment by Kumagor0** [comment]
I have similar error:

UserSchema.Instance.prototype.setPassword = function (password, cb) {
                       ^
TypeError: Cannot read property 'prototype' of undefined

I am a bit confused about what UserSchema.Instance is supposed to be, because neither MDN documentation on Classes nor Sequalize docs seem to mention it.

**Comment by danielsoner** [comment]
I have the same issue:
```
node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:85
    UserSchema.Instance.prototype.setPassword = function (password, cb) {
                       ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.attachToUser (/node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:85:24)
```

**Comment by fov42550564** [comment]
have any one resolve it?

**Comment by danielsoner** [comment]
Not yet, but I emailed the author yesterday and he responded asap that he will have a look.

**Comment by danielsoner** [comment]
Hi, any news with this issue?

**Comment by madhurjain** [comment]
Can you guys please upgrade to _passport-local-sequelize@0.8.0_ and try it out? I can then close this issue.

**Comment by daniloaf** [comment]
Hey, I'm using `0.8.0` and I'm having a similar problem when using `attachUser`:
```
node_modules/passport-local-sequelize/lib/passport-local-sequelize.js:82
    UserSchema.prototype.setPassword = function (password, cb) {
                                     ^
TypeError: Cannot set property 'setPassword' of undefined
```

Node version: `v8.0.0`
Sequelize version: `^3.30.4`

**Comment by madhurjain** [comment]
@daniloaf Please update to Sequelize version `4.4.2` or above

**Comment by daniloaf** [comment]
That solved the problem! Thanks, @madhurjain
