### ISSUE TITLE
TypeError: user.createStrategy is not a function

### ISSUE THREAD

**Issue by bharathvaj1995** [madhurjain/passport-local-sequelize#38]

**Comment by Sochil** [comment]
idk why i still have this issue

**Comment by Sochil** [comment]
passport.use(User.createStrategy());
                  ^

TypeError: User.createStrategy is not a function

**Comment by rohitt05** [comment]
TypeError: User.createStrategy is not a function 

I'm having the same problem

**Comment by delivey** [comment]
Having the same issue on Node.js v18.15.0

**Comment by prashant5025** [comment]
I ran into the same problem I solve it using this method:-

first you need to install passport-local-mongoose package
and then you have to add userschema plugin into you user model like this.
```js
const passportLocalMongoose  = require("passport-local-mongoose");

UserSchema.plugin(passportLocalMongoose);
```
