### ISSUE TITLE
Migration to Sequelize v5

### ISSUE THREAD

**Issue by leosia** [madhurjain/passport-local-sequelize#44]
After last Sequelize update many functions names was changed. See https://github.com/sequelize/sequelize/issues/9372#issuecomment-421382308

Thanks for this lib, it was very helpful.

**Comment by isTravis** [comment]
I'd also really like to see this happen. But, the larger question related to this that I have is: is this repo still maintained? There are a number of outstanding pull requests, and there have been no updates in over 2 years.

It's really been a valuable package - so thanks for all your hard work so far!

**Comment by isTravis** [comment]
@SaswatB Thanks so much for the PR updating the code for sequelize v5. @madhurjain, would it be possible to update the NPM package to reflect these updates? Thanks as always!

**Comment by isTravis** [comment]
@madhurjain Sorry to pester again - but any chance we could get a quick `npm publish` run so that @SaswatB's PR is pushed to npm? Thank you!

**Comment by madhurjain** [comment]
@isTravis Sure. Sorry I haven't been able to keep up. Will push in a couple of hours.

**Comment by madhurjain** [comment]
Pushed `passport-local-sequelize@0.9.0`
