### ISSUE TITLE
NPM package update

### ISSUE THREAD

**Issue by dbengsch** [madhurjain/passport-local-sequelize#48]
Would it be possible to publish a new version of the NPM package with the sequelize version update available in the master branch ?

Thanks in advance

**Comment by Miskamyasa** [comment]
need to be done!

**Comment by yanfaliupst** [comment]
any update on this? the current npm package is 4 years old. Would be awesome if you could push a new update with updated sequelize deps. TY!

**Comment by madhurjain** [comment]
Done!
https://www.npmjs.com/package/passport-local-sequelize

Sorry I am not able to keep up with this NPM package since I have stopped using Sequelize for my projects. I would be happy to take on some collaborators to maintain this package.
