### ISSUE TITLE
Please update the NPM package

### ISSUE THREAD

**Issue by theanimal666** [madhurjain/passport-local-sequelize#5]
First i'd liḱe to saý thanks for your great package!

Please push the lates version to NPM as my projects depends on the fix implemented in https://github.com/madhurjain/passport-local-sequelize/commit/30bba2f4f1d7fd6b3f9eb149e9097f0b3b6cbfdb

kind regards,
Chris

**Comment by madhurjain** [comment]
Thanks. Updated.

**Comment by theanimal666** [comment]
thank you very much
